services:
  # Определение сервисов для Docker Compose

  maildev:
    # Сервис для MailDev (инструмент для тестирования email)
    build:
      context: .
      dockerfile: maildev.Dockerfile
    # Строим образ из Dockerfile с именем maildev.Dockerfile в текущем контексте
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    # Пробрасываем порты для MailDev:
    # - ${MAIL_CLIENT_PORT}: порт для веб-интерфейса MailDev (1080)
    # - ${MAIL_PORT}: порт для SMTP сервера MailDev (1025)

  mongo:
    # Сервис для базы данных MongoDB
    image: mongo:7.0.14
    # Используем официальный образ MongoDB версии 7.0.14
    restart: always
    # Перезапускать контейнер всегда при сбое
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    # Устанавливаем переменные окружения для MongoDB:
    # - MONGO_INITDB_ROOT_USERNAME: имя пользователя базы данных, берется из переменной окружения DATABASE_USERNAME
    # - MONGO_INITDB_ROOT_PASSWORD: пароль пользователя базы данных, берется из переменной окружения DATABASE_PASSWORD
    volumes:
      - boilerplate-mongo-db:/data/db
    # Определяем том для хранения данных MongoDB
    ports:
      - ${DATABASE_PORT}:27017
    # Пробрасываем порт ${DATABASE_PORT} на порт 27017 контейнера

  mongo-express:
    # Сервис для Mongo Express (веб-интерфейс для управления MongoDB)
    image: mongo-express
    # Используем официальный образ Mongo Express
    restart: always
    # Перезапускать контейнер всегда при сбое
    ports:
      - 8081:8081
    # Пробрасываем порт 8081 на порт 8081 контейнера
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongo:${DATABASE_PORT}/
    # Устанавливаем переменные окружения для Mongo Express:
    # - ME_CONFIG_BASICAUTH_USERNAME: имя пользователя для базовой аутентификации, берется из переменной окружения DATABASE_USERNAME
    # - ME_CONFIG_BASICAUTH_PASSWORD: пароль для базовой аутентификации, берется из переменной окружения DATABASE_PASSWORD
    # - ME_CONFIG_MONGODB_URL: URL для подключения к MongoDB, использует переменные окружения DATABASE_USERNAME, DATABASE_PASSWORD и DATABASE_PORT

  # Uncomment to use redis
  # Раскомментируйте, чтобы использовать Redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379
  # Сервис для Redis (раскомментируйте, чтобы использовать Redis):
  # - Используем официальный образ Redis версии 7 на базе Alpine Linux
  # - Пробрасываем порт 6379 на порт 6379 контейнера

  api:
    # Сервис для API приложения
    build:
      context: .
      dockerfile: Dockerfile
    # Строим образ из Dockerfile с именем Dockerfile в текущем контексте
